export const posts = [
  {
    id: 1,
    title: "title1",
    img: "https://fakeimg.pl/250x100/",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    longDesc: "description for first Obj",
  },
  {
    id: 2,
    title: "title2",
    img: "https://fakeimg.pl/250x100/",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    longDesc: "description for first Obj",
  },
  {
    id: 3,
    title: "title3",
    img: "https://fakeimg.pl/250x100/",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    longDesc: "description for first Obj",
  },
  {
    id: 4,
    title: "title4",
    img: "https://fakeimg.pl/250x100/",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    longDesc: "description for first Obj",
  },
  {
    id: 5,
    title: "title4",
    img: "https://fakeimg.pl/250x100/",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    longDesc: "description for first Obj",
  },
  {
    id: 6,
    title: "title4",
    img: "https://fakeimg.pl/250x100/",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    longDesc: "description for first Obj",
  },
  {
    id: 7,
    title: "title4",
    img: "https://fakeimg.pl/250x100/",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    longDesc: "description for first Obj",
  },
  {
    id: 8,
    title: "title4",
    img: "https://fakeimg.pl/250x100/",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    longDesc: "description for first Obj",
  },
  {
    id: 5,
    title: "title4",
    img: "https://fakeimg.pl/250x100/",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    longDesc: "description for first Obj",
  },
  {
    id: 6,
    title: "title4",
    img: "https://fakeimg.pl/250x100/",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    longDesc: "description for first Obj",
  },
  {
    id: 7,
    title: "title4",
    img: "https://fakeimg.pl/250x100/",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    longDesc: "description for first Obj",
  },
  {
    id: 8,
    title: "title4",
    img: "https://fakeimg.pl/250x100/",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    longDesc: "description for first Obj",
  },
  {
    id: 6,
    title: "title4",
    img: "https://fakeimg.pl/250x100/",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    longDesc: "description for first Obj",
  },
  {
    id: 7,
    title: "title4",
    img: "https://fakeimg.pl/250x100/",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    longDesc: "description for first Obj",
  },
  {
    id: 8,
    title: "title9",
    img: "https://fakeimg.pl/250x100/",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    longDesc: "description for first Obj",
  },
  {
    id: 6,
    title: "title4",
    img: "https://fakeimg.pl/250x100/",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    longDesc: "description for first Obj",
  },
  {
    id: 7,
    title: "title4",
    img: "https://fakeimg.pl/250x100/",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    longDesc: "description for first Obj",
  },
  {
    id: 8,
    title: "title4",
    img: "https://fakeimg.pl/250x100/",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    longDesc: "description for first Obj",
  },
  {
    id: 6,
    title: "title4",
    img: "https://fakeimg.pl/250x100/",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    longDesc: "description for first Obj",
  },
  {
    id: 7,
    title: "title4",
    img: "https://fakeimg.pl/250x100/",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    longDesc: "description for first Obj",
  },
  {
    id: 8,
    title: "title10",
    img: "https://fakeimg.pl/250x100/",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    longDesc: "description for first Obj",
  },
];
